# Generated by Django 5.1.7 on 2025-03-23 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='category',
        ),
        migrations.AddField(
            model_name='skill',
            name='availability',
            field=models.CharField(default='Flexible', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='level',
            field=models.CharField(default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='skill',
            name='location',
            field=models.CharField(default='On-Campus', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_type',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='skill',
            name='sub_skill',
            field=models.CharField(default='Other', max_length=100),
        ),
    ]
