# Generated by Django 5.1.7 on 2025-03-24 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skillshare', '0002_remove_skill_category_skill_availability_skill_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='image',
        ),
        migrations.AddField(
            model_name='skill',
            name='iimage',
            field=models.ImageField(blank=True, null=True, upload_to='skill_images/'),
        ),
    ]
