# Generated by Django 5.1.7 on 2025-03-25 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('availability', models.TextField()),
                ('contact', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='care_providers/')),
            ],
        ),
        migrations.CreateModel(
            name='HealthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(upload_to='event_images/')),
                ('rsvp_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('symptoms', models.TextField()),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='torocare.careprovider')),
            ],
        ),
    ]
